### ISSUE TITLE
tagged release

### ISSUE THREAD

**Issue by q66** [project-spiel/speech-provider-espeak#1]
Since webkitgtk is going to use libspiel, this will probably come up a bunch of times; many distros have a policy against software without tagged releases and while the libraries do have them, none of the speech providers do, which means many are going to be reluctant against shipping it. Is there any plan to do so? I guess the espeak provider is the most important one (as that's what most people are using)

**Comment by q66** [comment]
I've got a bit of a head start and packaged it already (and tested it with webkit). I for now put the espeak provider in the user repository where there are looser requirements, but in longer run I'd like to have a functional provider in the same repo with the library..

**Comment by eeejay** [comment]
Here ya go! [SPEECH_PROVIDER_ESPEAK_0_1_0](https://github.com/project-spiel/speech-provider-espeak/releases/tag/SPEECH_PROVIDER_ESPEAK_0_1_0)

**Comment by q66** [comment]
thanks :)
